const jsonData = {
    "\u7684": "possessive, adjectival suffix",
    "\u4e00": "one; a, an; alone",
    "\u662f": "indeed, yes, right; to be; demonstrative pronoun, this, that",
    "\u4e0d": "no, not; un-; negative prefix",
    "\u4e86": "to finish; particle of completed action",
    "\u5728": "be at, in, on; consist in, rest",
    "\u4eba": "man; people; mankind; someone else",
    "\u6709": "have, own, possess; exist",
    "\u6211": "our, us, i, me, my, we",
    "\u4ed6": "other, another; he, she, it",
    "\u8fd9": "this, the, here",
    "\u4e2a": "numerary adjunct, piece; single",
    "\u4eec": "adjunct pronoun indicate plural",
    "\u4e2d": "central; center, middle; in the midst of; hit (target); attain",
    "\u6765": "come, coming; return, returning",
    "\u4e0a": "top; superior, highest; go up, send up",
    "\u5927": "big, great, vast, large, high",
    "\u4e3a": "do, handle, govern, act; be",
    "\u548c": "harmony, peace; peaceful, calm",
    "\u56fd": "nation, country, nation-state",
    "\u5730": "earth; soil, ground; region",
    "\u5230": "go to, arrive, been to",
    "\u4ee5": "by means of; thereby, therefore; consider as; in order to",
    "\u8bf4": "speak, say, talk; scold, upbraid",
    "\u65f6": "time, season; era, age, period",
    "\u8981": "necessary, essential; necessity",
    "\u5c31": "just, simply; to come, go to; to approach, near",
    "\u51fa": "go out, send out; stand; produce",
    "\u4f1a": "assemble, meet together; meeting",
    "\u53ef": "may, can, -able; possibly",
    "\u4e5f": "also; classical final particle of strong affirmation or identity",
    "\u4f60": "you, second person pronoun",
    "\u5bf9": "correct, right; facing, opposed",
    "\u751f": "life, living, lifetime; birth",
    "\u80fd": "to be able; can, permitted to; ability",
    "\u800c": "and; and then; and yet; but",
    "\u5b50": "offspring, child; fruit, seed of; 1st terrestrial branch",
    "\u90a3": "that, that one, those",
    "\u5f97": "obtain, get, gain, acquire",
    "\u4e8e": "in, on, at; go to; surname",
    "\u7740": "make move, take action",
    "\u4e0b": "under, underneath, below; down; inferior; bring down",
    "\u81ea": "self, private, personal; from",
    "\u4e4b": "marks preceding phrase as modifier of following phrase; it, him her, them; go to",
    "\u8fc7": "pass, pass through, go across",
    "\u53d1": "issue, dispatch, send out; hair",
    "\u540e": "queen, empress, sovereign; (simp. for ",
    "\u4f5c": "make; work; compose, write; act, perform",
    "\u91cc": "unit of distance; village; lane",
    "\u7528": "use, employ, apply, operate; use",
    "\u9053": "path, road, street; method, way",
    "\u884c": "go; walk; move, travel; circulate",
    "\u6240": "place, location; numerary adjunct",
    "\u7136": "yes, certainly; pledge, promise",
    "\u5bb6": "house, home, residence; family",
    "\u79cd": "seed; race, breed; to plant",
    "\u4e8b": "affair, matter, business; to serve; accident, incident",
    "\u6210": "completed, finished, fixed",
    "\u65b9": "a square, rectangle; a region; local",
    "\u591a": "much, many; more than, over",
    "\u7ecf": "classic works; pass through",
    "\u4e48": "interrogative particle; repetition of a tune small; tender",
    "\u53bb": "go away, leave, depart",
    "\u6cd5": "law, rule, regulation, statute; France, French",
    "\u5b66": "learning, knowledge; school",
    "\u5982": "if, supposing; as if; like, as",
    "\u90fd": "metropolis, capital; all, the whole; elegant, refined",
    "\u540c": "same, similar; together with",
    "\u73b0": "appear, manifest, become visible",
    "\u5f53": "bear, accept, undertake; just",
    "\u6ca1": "not, have not, none; drown, sink",
    "\u52a8": "move, happen; movement, action",
    "\u9762": "face; surface; plane; side, dimension",
    "\u8d77": "rise, stand up; go up; begin",
    "\u770b": "look, see; examine, scrutinize",
    "\u5b9a": "decide, settle, fix",
    "\u5929": "sky, heaven; god, celestial",
    "\u5206": "divide; small unit of time etc.",
    "\u8fd8": "still, yet, also, besides",
    "\u8fdb": "advance, make progress, enter",
    "\u597d": "good, excellent, fine; well",
    "\u5c0f": "small, tiny, insignificant",
    "\u90e8": "part, division, section",
    "\u5176": "his, her, its, their; that",
    "\u4e9b": "little, few; rather, somewhat",
    "\u4e3b": "master, chief owner; host; lord",
    "\u6837": "shape, form, pattern, style",
    "\u7406": "reason, logic; manage",
    "\u5fc3": "heart; mind, intelligence; soul",
    "\u5979": "she, her",
    "\u672c": "root, origin, source; basis",
    "\u524d": "in front, forward; preceding",
    "\u5f00": "open; initiate, begin, start",
    "\u4f46": "only; but, however, yet, still",
    "\u56e0": "cause, reason; by; because (of)",
    "\u53ea": "only, just, simply",
    "\u4ece": "from, by, since, whence, through",
    "\u60f3": "think, speculate, plan, consider",
    "\u5b9e": "real, true; honest, sincere",
    "\u65e5": "sun; day; daytime",
    "\u519b": "army, military; soldiers, troops",
    "\u8005": "that which; he who; those who",
    "\u610f": "thought, idea, opinion; think",
    "\u65e0": "negative, no, not; KangXi radical 71",
    "\u529b": "power, capability, influence",
    "\u5b83": "it; other",
    "\u4e0e": "and; with; to; for; give, grant",
    "\u957f": "long; length; excel in; leader",
    "\u628a": "hold, take; guard; regard as",
    "\u673a": "desk; machine; moment",
    "\u5341": "ten, tenth; complete; perfect",
    "\u6c11": "people, subjects, citizens",
    "\u7b2c": "sequence, number; grade, degree",
    "\u516c": "fair, equitable; public; duke",
    "\u6b64": "this, these; in this case, then",
    "\u5df2": "already; finished; stop",
    "\u5de5": "labor, work; worker, laborer",
    "\u4f7f": "cause, send on a mission, order; envoy, messenger, ambassador",
    "\u60c5": "feeling, sentiment, emotion",
    "\u660e": "bright, light, brilliant; clear",
    "\u6027": "nature, character, sex",
    "\u77e5": "know, perceive, comprehend",
    "\u5168": "maintain, keep whole or intact",
    "\u4e09": "three",
    "\u53c8": "and, also, again, in addition",
    "\u5173": "frontier pass; close; relation",
    "\u70b9": "dot, speck, spot; point, degree",
    "\u6b63": "right, proper, correct",
    "\u4e1a": "profession, business; GB radical 111",
    "\u5916": "out, outside, external; foreign",
    "\u5c06": "will, going to, future; general",
    "\u4e24": "two, both, pair, couple; ounce",
    "\u9ad8": "high, tall; lofty, elevated",
    "\u95f4": "midpoint, space; place, locality",
    "\u7531": "cause, reason; from",
    "\u95ee": "ask about, inquire after",
    "\u5f88": "very, quite, much",
    "\u6700": "most, extremely, exceedingly",
    "\u91cd": "heavy, weighty; double",
    "\u7269": "thing, substance, creature",
    "\u624b": "hand",
    "\u5e94": "should, ought to, must",
    "\u6218": "war, fighting, battle",
    "\u5411": "toward, direction, trend",
    "\u5934": "head; top; chief, first; boss",
    "\u6587": "literature, culture, writing",
    "\u4f53": "body; group, class, body, unit; inferior",
    "\u653f": "government, political affairs",
    "\u7f8e": "beautiful, pretty; pleasing",
    "\u76f8": "mutual, reciprocal, each other",
    "\u89c1": "see, observe, behold; perceive",
    "\u5229": "gains, advantage, profit, merit",
    "\u4ec0": "file of ten soldiers; mixed, miscellaneous",
    "\u4e8c": "two; twice",
    "\u7b49": null,
    "\u4ea7": "give birth, bring forth, produce",
    "\u6216": "or, either, else; perhaps, maybe",
    "\u65b0": "new, recent, fresh, modern",
    "\u5df1": "self, oneself; personal, private; 6th heavenly stem",
    "\u5236": "system; establish; overpower",
    "\u8eab": "body; trunk, hull; rad. no. 158",
    "\u679c": "fruit; result",
    "\u52a0": "add to, increase, augment",
    "\u897f": "west(ern); westward, occident",
    "\u65af": "this, thus, such; to lop off; emphatic particle",
    "\u6708": "moon; month; KangXi radical 74",
    "\u8bdd": "speech, talk, language; dialect",
    "\u5408": "combine, unite, join; gather",
    "\u56de": "return, turn around; a time",
    "\u7279": "special, unique, distinguished",
    "\u4ee3": "replace, replacement (of person or generation); era, generation",
    "\u5185": "inside",
    "\u4fe1": "trust, believe; letter",
    "\u8868": "show, express, manifest, display",
    "\u5316": "change, convert, reform; -ize",
    "\u8001": "old, aged; experienced",
    "\u7ed9": "give; by, for",
    "\u4e16": "generation; world; era",
    "\u4f4d": "throne; position, post; rank, status; seat",
    "\u6b21": "order, sequence; next",
    "\u5ea6": "degree, system; manner; to consider",
    "\u95e8": "gate, door, entrance, opening",
    "\u4efb": "trust to, rely on, appoint; to bear, duty, office; allow",
    "\u5e38": "common, normal, frequent, regular",
    "\u5148": "first, former, previous",
    "\u6d77": "sea, ocean; maritime",
    "\u901a": "pass through, common, communicate",
    "\u6559": "teach, class",
    "\u513f": "son, child; KangXi radical 10",
    "\u539f": "source, origin, beginning",
    "\u4e1c": "east, eastern, eastward",
    "\u58f0": "sound, voice, noise; tone; music",
    "\u63d0": "hold in hand; lift in hand",
    "\u7acb": "stand; let stand; establish, set",
    "\u53ca": "extend; reach; come up to; and",
    "\u6bd4": "to compare, liken; comparison; than",
    "\u5458": "member; personnel, staff member",
    "\u89e3": "loosen, unfasten, untie; explain",
    "\u6c34": "water, liquid, lotion, juice",
    "\u540d": "name, rank, title, position",
    "\u771f": "real, actual, true, genuine",
    "\u8bba": "debate; discuss; discourse",
    "\u5904": "place, locale; department",
    "\u8d70": "walk, go on foot; run; leave",
    "\u4e49": "right conduct, righteousness",
    "\u5404": "each, individually, every, all",
    "\u5165": "enter, come in(to), join",
    "\u51e0": "small table",
    "\u53e3": "mouth; open end; entrance, gate",
    "\u8ba4": "recognize, know, understand",
    "\u6761": "clause, condition; string, stripe",
    "\u5e73": "flat, level, even; peaceful",
    "\u7cfb": "system; line, link, connection",
    "\u6c14": "steam, vapor; KangXi radical 84",
    "\u9898": "forehead; title, headline; theme",
    "\u6d3b": "live, exist, survive; lively",
    "\u5c14": "you; that, those; final particle",
    "\u66f4": "more, still further, much more",
    "\u522b": "separate, other; do not",
    "\u6253": "strike, hit, beat; fight; attack",
    "\u5973": "woman, girl; feminine; rad. 38",
    "\u53d8": "change, transform, alter; rebel",
    "\u56db": "four",
    "\u795e": "spirit, god, supernatural being",
    "\u603b": "collect; overall, altogether",
    "\u4f55": "what, why, where, which, how",
    "\u7535": "electricity; electric; lightning",
    "\u6570": "number; several, count; fate",
    "\u5b89": "peaceful, tranquil, quiet",
    "\u5c11": "few, less, inadequate",
    "\u62a5": "report, tell, announce",
    "\u624d": "talent, ability; just, only",
    "\u7ed3": "knot, tie; join, connect",
    "\u53cd": "reverse, opposite, contrary, anti",
    "\u53d7": "receive, accept, get; bear, stand",
    "\u76ee": "eye; look, see; division, topic",
    "\u592a": "very, too, much; big; extreme",
    "\u91cf": "measure, quantity, capacity",
    "\u518d": "again, twice, re-",
    "\u611f": "feel, perceive, emotion",
    "\u5efa": "build, establish, erect, found",
    "\u52a1": "affairs, business; must, should",
    "\u505a": "work, make; act",
    "\u63a5": "receive; continue; catch; connect",
    "\u5fc5": "surely, most certainly; must",
    "\u573a": "open space, field, market",
    "\u4ef6": "numerary adjunct for article; matter",
    "\u8ba1": "plan, plot; strategem; scheme",
    "\u7ba1": "pipe, tube, duct; woodwind music",
    "\u671f": "period of time; date; time limit",
    "\u5e02": "market, fair; city, town; trade",
    "\u76f4": "straight, erect, vertical",
    "\u5fb7": "ethics, morality, virtue",
    "\u8d44": "property; wealth; capital",
    "\u547d": "life; destiny, fate, luck; an order, instruction",
    "\u5c71": "mountain, hill, peak",
    "\u91d1": "gold; metals in general; money",
    "\u6307": "finger, toe; point, indicate",
    "\u514b": "gram; overcome; transliteration",
    "\u8bb8": "allow, permit; promise; betroth",
    "\u7edf": "govern, command, control; unite",
    "\u533a": "area, district, region, ward",
    "\u4fdd": "protect, safeguard, defend, care",
    "\u81f3": "reach, arrive; extremely, very",
    "\u961f": "team, group; army unit",
    "\u5f62": "form, shape, appearance",
    "\u793e": "god of the soil and altars to him; group of families; company, society",
    "\u4fbf": "convenience, ease; expedient",
    "\u7a7a": "empty, hollow, bare, deserted",
    "\u51b3": "decide, determine, judge",
    "\u6cbb": "govern, regulate, administer",
    "\u5c55": "open, unfold; stretch, extend",
    "\u9a6c": "horse; surname; KangXi radical 187",
    "\u79d1": "section, department, science",
    "\u53f8": "take charge of, control, manage; officer",
    "\u4e94": "five; surname",
    "\u57fa": "foundation, base",
    "\u773c": "eye; eyelet, hole, opening",
    "\u4e66": "book, letter, document; writings",
    "\u975e": "not, negative, non-; oppose",
    "\u5219": "rule, law, regulation; grades",
    "\u542c": "hear; understand; obey, comply",
    "\u767d": "white; pure, unblemished; bright",
    "\u5374": "still, but; decline; retreat",
    "\u754c": "boundary, limit; domain; society; the world",
    "\u8fbe": "arrive at, reach; intelligent; smooth, slippery",
    "\u5149": "light, brilliant, shine; only",
    "\u653e": "put, release, free, liberate",
    "\u5f3a": "strong, powerful, energetic",
    "\u5373": "promptly, quickly, immediately",
    "\u50cf": "a picture, image, figure; to resemble",
    "\u96be": "difficult, arduous, hard; unable",
    "\u4e14": "moreover, also (post-subject); about to, will soon (pre-verb)",
    "\u6743": "power, right, authority",
    "\u601d": "think, consider, ponder; final particle",
    "\u738b": "king, ruler; royal; surname",
    "\u8c61": "elephant; ivory; figure, image",
    "\u5b8c": "complete, finish, settle; whole",
    "\u8bbe": "build; establish; display",
    "\u5f0f": "style, system, formula, rule",
    "\u8272": "color, tint, hue, shade; form, body; beauty, desire for beauty",
    "\u8def": "road, path, street; journey",
    "\u8bb0": "record; keep in mind, remember",
    "\u5357": "south; southern part; southward",
    "\u54c1": "article, product, commodity",
    "\u4f4f": "reside, live at, dwell, lodge; stop",
    "\u544a": "tell, announce, inform; accuse",
    "\u7c7b": "class, group, kind, category",
    "\u6c42": "seek; demand, request; beseech",
    "\u636e": "to occupy, take possession of; a base, position",
    "\u7a0b": "journey, trip; schedule, agenda",
    "\u5317": "north; northern; northward",
    "\u8fb9": "edge, margin, side, border",
    "\u6b7b": "die; dead; death",
    "\u5f20": "stretch, extend, expand; sheet",
    "\u8be5": "should, ought to, need to",
    "\u4ea4": "mix; intersect; exchange, communicate; deliver",
    "\u89c4": "rules, regulations, customs, law",
    "\u4e07": "ten thousand; innumerable",
    "\u53d6": "take, receive, obtain; select",
    "\u62c9": "pull, drag; seize, hold; lengthen",
    "\u683c": "pattern, standard, form; style",
    "\u671b": "to look at, look forward; to hope, expect",
    "\u89c9": "to wake up from sleep; conscious",
    "\u672f": "art, skill, special feat; method, technique",
    "\u9886": "neck; collar; lead, guide",
    "\u5171": "together with, all, total; to share",
    "\u786e": "sure, certain; real, true",
    "\u4f20": "summon; propagate, transmit",
    "\u5e08": "teacher, master, specialist",
    "\u89c2": "see, observe, view; appearance",
    "\u6e05": "clear, pure, clean; peaceful",
    "\u4eca": "now, today, modern era",
    "\u5207": "cut, mince, slice, carve",
    "\u9662": "courtyard, yard, court; school",
    "\u8ba9": "allow, permit, yield, concede",
    "\u8bc6": "recognize, understand, know",
    "\u5019": "wait; expect; visit; greet",
    "\u5e26": "belt, girdle, band, strap, zone",
    "\u5bfc": "direct, guide, lead, conduct",
    "\u4e89": "dispute, fight, contend, strive",
    "\u8fd0": "run; simplified form of ",
    "\u7b11": "smile, laugh, giggle; snicker",
    "\u98de": "fly; go quickly; dart; high",
    "\u98ce": "wind; air; manners, atmosphere",
    "\u6b65": "step, pace; walk, stroll",
    "\u6539": "change, alter; improve, remodel",
    "\u6536": "gather together, collect; harvest",
    "\u6839": "root, base(d on); foundation",
    "\u5e72": "oppose, offend; invade; dried",
    "\u9020": "construct, build, make, begin; prepare",
    "\u8a00": "words, speech; speak, say",
    "\u8054": "connect, join; associate, ally",
    "\u6301": "sustain, support; hold, grasp",
    "\u7ec4": "class; section, department",
    "\u6bcf": "every, each",
    "\u6d4e": "help, aid, relieve; ferry, cross",
    "\u8f66": "cart, vehicle; carry in cart",
    "\u4eb2": "relatives, parents; intimate the hazel nut or filbert tree a thorny tree",
    "\u6781": "extreme, utmost, furthest, final",
    "\u6797": "forest, grove; surname",
    "\u670d": "clothes; wear, dress",
    "\u5feb": "rapid, quick, speedy, fast; soon",
    "\u529e": "manage, do, handle; deal with",
    "\u8bae": "consult, talk over, discuss",
    "\u5f80": "go, depart; past, formerly",
    "\u5143": "first; dollar; origin; head",
    "\u82f1": "petal, flower, leaf; brave, a hero; England, English",
    "\u58eb": "scholar, gentleman; soldier",
    "\u8bc1": "prove, confirm, verify; proof",
    "\u8fd1": "near, close; approach; intimate",
    "\u5931": "lose; make mistake, neglect",
    "\u8f6c": "shift, move, turn",
    "\u592b": "man, male adult, husband; those",
    "\u4ee4": null,
    "\u51c6": "approve, allow, permit; in accord",
    "\u5e03": "cotton cloth, textiles, linen",
    "\u59cb": "begin, start; then, only then",
    "\u600e": "what? why? how?",
    "\u5462": "interrogative or emphatic final; (Cant.) this",
    "\u5b58": "exist, live, be; survive; remain",
    "\u672a": "not yet; 8th terrestrial branch",
    "\u8fdc": "distant, remote, far; profound",
    "\u53eb": "cry, shout; hail, greet, call",
    "\u53f0": "platform; unit; term of address",
    "\u5355": "single, individual, only; lone",
    "\u5f71": "shadow; image, reflection; photograph",
    "\u5177": "tool, implement; draw up, write",
    "\u7f57": "net for catching birds; gauze",
    "\u5b57": "letter, character, word",
    "\u7231": "love, be fond of, like",
    "\u51fb": "strike, hit, beat; attack, fight",
    "\u6d41": "flow, circulate, drift; class",
    "\u5907": "prepare, ready, perfect",
    "\u5175": "soldier, troops",
    "\u8fde": "join, connect; continuous; even",
    "\u8c03": "transfer, move, change; tune",
    "\u6df1": "deep; depth; far; very, extreme",
    "\u5546": "commerce, business, trade",
    "\u7b97": "count, calculate, figure; plan",
    "\u8d28": "matter, material, substance",
    "\u56e2": "sphere, ball, circle; mass, lump",
    "\u96c6": "assemble, collect together",
    "\u767e": "one hundred; numerous, many",
    "\u9700": "need, require, must",
    "\u4ef7": "price, value",
    "\u82b1": "flower; blossoms",
    "\u515a": "political party, gang, faction",
    "\u534e": "flowery; illustrious; Chinese",
    "\u57ce": "castle; city, town; municipality",
    "\u77f3": "stone, rock, mineral; rad. 112",
    "\u7ea7": "level, rank, class; grade",
    "\u6574": "orderly, neat, tidy; whole",
    "\u5e9c": "prefecture; prefect; government",
    "\u79bb": "rare beast; strange; elegant",
    "\u51b5": "condition, situation; furthermore",
    "\u4e9a": "Asia; second",
    "\u8bf7": "ask, request; invite; please",
    "\u6280": "skill, ability, talent, ingenuity",
    "\u9645": "border, boundary, juncture",
    "\u7ea6": "treaty, agreement, covenant",
    "\u793a": "show, manifest; demonstrate",
    "\u590d": "return; repeat; repeatedly",
    "\u75c5": "illness, sickness, disease",
    "\u606f": "rest, put stop to, end, cease",
    "\u7a76": "examine, investigate",
    "\u7ebf": "line, thread, wire; clue",
    "\u4f3c": "resemble, similar to; as if, seem",
    "\u5b98": "official, public servant",
    "\u706b": "fire, flame; burn; anger, rage",
    "\u65ad": "sever, cut off; interrupt",
    "\u7cbe": "essence; semen; spirit",
    "\u6ee1": "fill; full, satisfied",
    "\u652f": "disperse, pay; support; branch",
    "\u89c6": "look at, inspect, observe, see",
    "\u6d88": "vanish, die out; melt away",
    "\u8d8a": "exceed, go beyond; the more ...",
    "\u5668": "receptacle, vessel; instrument",
    "\u5bb9": "looks, appearance; figure, form",
    "\u7167": "shine, illumine, reflect",
    "\u987b": "must, have to, necessary",
    "\u4e5d": "nine",
    "\u589e": "increase, add to, augment",
    "\u7814": "grind, rub; study, research",
    "\u5199": "write; draw, sketch; compose",
    "\u79f0": "call; name, brand; address; say",
    "\u4f01": "plan a project; stand on tiptoe",
    "\u516b": "eight; all around, all sides",
    "\u529f": "achievement, merit, good result",
    "\u5417": "final interrogative particle",
    "\u5305": "wrap, pack, bundle; package",
    "\u7247": "slice, splinter, strip; rad. 91",
    "\u53f2": "history, chronicle, annals",
    "\u59d4": "appoint, send, commission",
    "\u4e4e": "interrogative or exclamatory final particle",
    "\u67e5": "investigate, examine, seek into",
    "\u8f7b": "light; easy, simple; gentle",
    "\u6613": "change; easy",
    "\u65e9": "early; soon; morning",
    "\u66fe": "already; sign of past",
    "\u9664": "eliminate, remove, except",
    "\u519c": "agriculture, farming; farmer",
    "\u627e": "search, seek, look for; find",
    "\u88c5": "dress, clothes, attire; fill",
    "\u5e7f": "wide, extensive, broad; rad. 53",
    "\u663e": "manifest, display; evident, clear",
    "\u5427": "emphatic final particle",
    "\u963f": null,
    "\u674e": "plum; judge; surname",
    "\u6807": "mark, symbol, label, sign; stand the bole of a tree",
    "\u8c08": "talk; conversation; surname",
    "\u5403": "eat; drink; suffer, endure, bear",
    "\u56fe": "diagram; chart, map, picture",
    "\u5ff5": "think of, recall, study",
    "\u516d": "number six",
    "\u5f15": "to pull, draw out, attract; to stretch",
    "\u5386": "history; calendar",
    "\u9996": "head; first; leader, chief; a poem",
    "\u533b": "cure, heal; doctor, medical",
    "\u5c40": "bureau, office; circumstance",
    "\u7a81": "suddenly, abruptly, unexpectedly",
    "\u4e13": "monopolize, take sole possession",
    "\u8d39": "expenses, expenditures, fee",
    "\u53f7": "mark, sign; symbol; number",
    "\u5c3d": "exhaust, use up; deplete",
    "\u53e6": "another, separate, other",
    "\u5468": "Zhou dynasty; circumference",
    "\u8f83": "compare; comparatively, more",
    "\u6ce8": "concentrate, focus, direct",
    "\u8bed": "language, words; saying, expression",
    "\u4ec5": "only, merely, solely, just",
    "\u8003": "examine, test; investigate",
    "\u843d": "fall, drop; net income, surplus",
    "\u9752": "blue, green, black; young",
    "\u968f": "follow, listen to, submit to",
    "\u9009": "choose, select; elect; election",
    "\u5217": "a line; to arrange in order, classify",
    "\u6b66": "military; martial, warlike",
    "\u7ea2": "red, vermillion; blush, flush",
    "\u54cd": "make sound, make noise; sound",
    "\u867d": "although, even if",
    "\u63a8": "push, expel; push forward",
    "\u52bf": "power, force; tendency",
    "\u53c2": "take part in, intervene; ginseng",
    "\u5e0c": "rare; hope, expect, strive for",
    "\u53e4": "old, classic, ancient",
    "\u4f17": "multitude, crowd; masses, public",
    "\u6784": "frame, building, structure",
    "\u623f": "house, building; room",
    "\u534a": "half",
    "\u8282": "knot, node, joint; section",
    "\u571f": "soil, earth; items made of earth",
    "\u6295": "throw, cast, fling, pitch; jump",
    "\u67d0": "certain thing or person",
    "\u6848": "table, bench; legal case",
    "\u9ed1": "black; dark; evil, sinister",
    "\u7ef4": "maintain, preserve, safeguard",
    "\u9769": "leather, animal hides; rad. 177",
    "\u5212": "to row or paddle boat; to scratch",
    "\u654c": "enemy, foe, rival; resist",
    "\u81f4": "send, deliver, present; cause",
    "\u9648": "exhibit, display; plead; a surname",
    "\u5f8b": "statute, principle, regulation",
    "\u8db3": "foot; attain, satisfy, enough",
    "\u6001": "manner, bearing, attitude",
    "\u62a4": "protect, guard, defend, shelter",
    "\u4e03": "seven",
    "\u5174": "thrive, prosper, flourish",
    "\u6d3e": "school of thought, sect, branch",
    "\u5b69": "baby, child; children",
    "\u9a8c": "test, examine, inspect; verify",
    "\u8d23": null,
    "\u8425": "encampment, barracks; manage",
    "\u661f": "a star, planet; any point of light",
    "\u591f": "enough, adequate",
    "\u7ae0": "composition; chapter, section",
    "\u97f3": "sound, tone, pitch, pronunciation",
    "\u8ddf": "heel; to follow, accompany; with",
    "\u5fd7": "purpose, will, determination; annals",
    "\u5e95": "bottom, underneath, underside",
    "\u7ad9": "stand up; a stand, station",
    "\u4e25": "strict, rigorous, rigid; stern",
    "\u5df4": "greatly desire, anxiously hope",
    "\u4f8b": "precedent, example; regulation",
    "\u9632": "defend; prevent; embankment",
    "\u65cf": "a family clan, ethnic group, tribe",
    "\u4f9b": "supply, provide for; offer in worship",
    "\u6548": "result, effect; effectiveness",
    "\u7eed": "continue, carry on; succeed",
    "\u65bd": "grant, bestow; give; act; name",
    "\u7559": "stop, halt; stay, detain, keep",
    "\u8bb2": "explain; discuss; talk",
    "\u578b": "pattern, model, type; law; mold",
    "\u6599": "consider, conjecture; materials, ingredients",
    "\u7ec8": "end; finally, in the end",
    "\u7b54": "answer, reply; return; assent to",
    "\u7d27": "tense, tight, taut; firm, secure",
    "\u9ec4": "yellow; surname",
    "\u7edd": "to cut, sever, break off, terminate",
    "\u5947": "strange, unusual, uncanny, occult",
    "\u5bdf": "examine, investigate; notice",
    "\u6bcd": "mother; female elders; female",
    "\u4eac": "capital city",
    "\u6bb5": "section, piece, division",
    "\u4f9d": "rely on, be set in; consent, obey a wish",
    "\u6279": "comment, criticize; wholesale",
    "\u7fa4": "(same as ",
    "\u9879": "neck, nape of neck; sum; funds",
    "\u6545": "ancient, old; reason, because",
    "\u6309": "put hand on, press down with hand",
    "\u6cb3": "river; stream; yellow river",
    "\u7c73": "hulled or husked uncooked rice",
    "\u56f4": "surround, encircle, corral",
    "\u6c5f": "large river; yangzi; surname",
    "\u7ec7": "weave, knit; organize, unite",
    "\u5bb3": "injure, harm; destroy, kill",
    "\u6597": "Chinese peck; liquid measure",
    "\u53cc": "set of two, pair, couple; both",
    "\u5883": "boundary, frontier; area, region",
    "\u5ba2": "guest, traveller; customer",
    "\u7eaa": "record, annal, historical account",
    "\u91c7": "collect, gather; pick, pluck",
    "\u4e3e": "raise, lift up; recommend",
    "\u6740": "kill, slaughter, murder; hurt",
    "\u653b": "attack, assault; criticize",
    "\u7236": "father; KangXi radical 88",
    "\u82cf": null,
    "\u5bc6": "dense, thick, close; intimate",
    "\u4f4e": "low; to lower, hang, bend, bow",
    "\u671d": "dynasty; morning",
    "\u53cb": "friend, companion; fraternity",
    "\u8bc9": "accuse; sue; inform; narrate",
    "\u6b62": "stop, halt, desist; detain",
    "\u7ec6": "fine, tiny; slender, thin",
    "\u613f": "sincere, honest, virtuous",
    "\u5343": "thousand; many, numerous; very; (Cant.) a cheater, swindler",
    "\u503c": "price",
    "\u4ecd": "yet, still, as ever; again; keep -ing, continuing",
    "\u7537": "male, man; son; baron; surname",
    "\u94b1": "money, currency, coins",
    "\u7834": "break, ruin, destroy; rout",
    "\u7f51": "net; network; KangXi radical 122",
    "\u70ed": "hot; heat; fever; restless; zeal",
    "\u52a9": "help, aid, assist",
    "\u5012": "fall over; lie down; take turns",
    "\u80b2": "produce, give birth to; educate",
    "\u5c5e": "class, category, type; belong to",
    "\u5750": "sit; seat; ride, travel by",
    "\u5e1d": "supreme ruler, emperor; god",
    "\u9650": "boundary, limit, line",
    "\u8239": "ship, boat, vessel",
    "\u8138": "face; cheek; reputation",
    "\u804c": "duty, profession; office, post",
    "\u901f": "quick, prompt, speedy",
    "\u523b": "carve, engrave; quarter hour",
    "\u4e50": "happy, glad; enjoyable; music",
    "\u5426": "not, no, negative; final particle",
    "\u521a": "hard, tough, rigid, strong",
    "\u5a01": "pomp, power; powerful; dominate",
    "\u6bdb": "hair, fur, feathers; coarse",
    "\u72b6": "form; appearance; shape; official",
    "\u7387": "to lead; ratio; rate; limit",
    "\u751a": "great extent; considerably",
    "\u72ec": "alone, single, solitary, only",
    "\u7403": "ball, sphere, globe; round",
    "\u822c": "sort, manner, kind, category",
    "\u666e": "universal, general, widespread",
    "\u6015": "to fear, be afraid of; apprehensive",
    "\u5f39": "pellet, bullet, shot, shell",
    "\u6821": "school; military field officer",
    "\u82e6": "bitter; hardship, suffering",
    "\u521b": "establish, create; knife cut",
    "\u5047": "falsehood, deception; vacation",
    "\u4e45": "long time (ago); time passage, grow late",
    "\u9519": "error, blunder, mistake; wrong",
    "\u627f": "inherit, receive; succeed",
    "\u5370": "print, seal, stamp, chop, mark",
    "\u665a": "night, evening; late",
    "\u5170": "orchid; elegant, graceful",
    "\u8bd5": "test, try, experiment",
    "\u80a1": "thighs, haunches, rump; share",
    "\u62ff": "take, hold, grasp; bring; with",
    "\u8111": "brain",
    "\u9884": "prepare, arrange; in advance",
    "\u8c01": "who? whom? whose? anyone?",
    "\u76ca": "profit, benefit; advantage",
    "\u9633": null,
    "\u82e5": "if, supposing, assuming; similar",
    "\u54ea": "which? where? how?",
    "\u5fae": "small, prefix micro-, trifling",
    "\u5c3c": "Buddhist nun; transliteration",
    "\u7ee7": "continue, maintain, carry on",
    "\u9001": "see off, send off; dispatch, give",
    "\u6025": "quick, quickly; urgent, pressing",
    "\u8840": "blood; radical number 143",
    "\u60ca": "frighten, surprise, startle",
    "\u4f24": "wound, injury; fall ill from",
    "\u7d20": "white (silk); plain; vegetarian; formerly; normally",
    "\u836f": "leaf of Dahurian angelica plant; medicine",
    "\u9002": "go, reach; appropriate, suitable",
    "\u6ce2": "waves, breakers; undulations",
    "\u591c": "night, dark; in night; by night",
    "\u7701": "province; save, economize",
    "\u521d": "beginning, initial, primary",
    "\u559c": "like, love, enjoy; joyful thing",
    "\u536b": "guard, protect, defend",
    "\u6e90": "spring; source, head; surname",
    "\u98df": "eat; meal; food; KangXi radical number 184",
    "\u9669": "narrow pass, strategic point",
    "\u5f85": "treat, entertain, receive; wait",
    "\u8ff0": "narrate, state, express",
    "\u9646": "land, continental; army",
    "\u4e60": "practice; flapping wings",
    "\u7f6e": "place, lay out; set aside",
    "\u5c45": "live, dwell, reside, sit",
    "\u52b3": "labor, toil, do manual work",
    "\u8d22": "wealth, valuables, riches",
    "\u73af": "jade ring or bracelet; ring",
    "\u6392": "row, rank, line",
    "\u798f": "happiness, good fortune, blessing",
    "\u7eb3": "admit, take, receive, accept",
    "\u6b22": "happy, pleased, glad; joy; enjoy",
    "\u96f7": "thunder",
    "\u8b66": "guard, watch; alert, alarm",
    "\u83b7": "obtain, get, receive; seize",
    "\u6a21": "model, standard, pattern; copy",
    "\u5145": "fill, be full, supply",
    "\u8d1f": "load, burden; carry, bear",
    "\u4e91": "say, speak; clouds",
    "\u505c": "stop, suspend, delay; suitable",
    "\u6728": "tree; wood, lumber; wooden",
    "\u6e38": "to swim; float, drift; wander, roam",
    "\u9f99": "dragon; symbolic of emperor",
    "\u6811": "tree; plant; set up, establish",
    "\u7591": "doubt, question, suspect",
    "\u5c42": "storey, layer, floor, stratum",
    "\u51b7": "cold, cool; lonely",
    "\u6d32": "continent; island; islet",
    "\u51b2": "soar; pour boiling water over",
    "\u5c04": "shoot, eject, issue forth, emit",
    "\u7565": "approximately, roughly; outline",
    "\u8303": "surname; bee-like insect",
    "\u7adf": "finally, after all, at last",
    "\u53e5": "sentence",
    "\u5ba4": "room, home, house, chamber",
    "\u5f02": "different, unusual, strange",
    "\u6fc0": "arouse, excite, incite; quickly",
    "\u6c49": "Chinese people; Chinese language",
    "\u6751": "village, hamlet; uncouth, vulgar",
    "\u54c8": "sound of laughter",
    "\u7b56": "scheme, plan; to whip; urge",
    "\u6f14": "perform, put on; exercise",
    "\u7b80": "simple, terse, succinct, a letter",
    "\u5361": "card, punch card; calorie",
    "\u7f6a": "crime, sin, vice; evil; hardship",
    "\u5224": "judge; discriminate; conclude",
    "\u62c5": "carry, bear, undertake",
    "\u5dde": "administrative division, state",
    "\u9759": "quiet, still, motionless; gentle",
    "\u9000": "step back, retreat, withdraw",
    "\u65e2": "already; de facto; since; then",
    "\u8863": "clothes, clothing; cover, skin",
    "\u5b97": "lineage, ancestry; ancestor, clan",
    "\u79ef": "accumulate, store up, amass",
    "\u4f59": "I, my, me; surname; surplus",
    "\u75db": "pain, ache; sorry, sad; bitter",
    "\u68c0": "check; examine",
    "\u5dee": "to differ; different, wrong; nearly, almost; an officer",
    "\u5bcc": "abundant, ample; rich, wealthy",
    "\u7075": "spirit, soul; spiritual world",
    "\u534f": "be united; cooperate",
    "\u89d2": "horn; angle, corner; point",
    "\u5360": "divine; observe; versify",
    "\u914d": "match, pair; equal; blend",
    "\u5f81": "invade, attack, conquer",
    "\u4fee": "study; repair; cultivate",
    "\u76ae": "skin, hide, fur, feather; outer",
    "\u6325": "direct; wipe away; squander",
    "\u80dc": "victory; excel, be better than",
    "\u964d": "descend, fall, drop; lower, down",
    "\u9636": "stairs, steps; rank, degree",
    "\u5ba1": "examine, investigate; judge",
    "\u6c89": "sink, submerge; addicted to",
    "\u575a": "hard, strong, firm; resolute",
    "\u5584": "good, virtuous, charitable, kind",
    "\u5988": "mother, mama",
    "\u5218": "surname; kill, destroy",
    "\u8bfb": "read, study; pronounce",
    "\u554a": "exclamatory particle",
    "\u8d85": "jump over, leap over; surpass",
    "\u514d": "spare; excuse from; evade",
    "\u538b": "press; oppress; crush; pressure",
    "\u94f6": "silver; cash, money, wealth",
    "\u4e70": "buy, purchase; bribe, persuade",
    "\u7687": "royal, imperial; ruler, superior",
    "\u517b": "raise, rear, bring up; support",
    "\u4f0a": "third person pronoun; he, she, this, that",
    "\u6000": "bosom, breast; carry in bosom",
    "\u6267": "hold in hand; keep; carry out",
    "\u526f": "assist; supplement; assistant",
    "\u4e71": "confusion, state of chaos, revolt",
    "\u6297": "resist, oppose, defy, reject",
    "\u72af": "commit crime, violate; criminal",
    "\u8ffd": "pursue, chase after; expel",
    "\u5e2e": "help, assist; defend; shoe upper",
    "\u5ba3": "declare, announce, proclaim",
    "\u4f5b": "Buddha; of Buddhism; merciful person; Buddhist image; the dead (Jap.)",
    "\u5c81": "year; age; harvest",
    "\u822a": "sail; navigate; ship, boat",
    "\u4f18": "superior, excellent; actor",
    "\u602a": "strange, unusual, peculiar",
    "\u9999": "fragrant, sweet smelling, incense",
    "\u8457": "manifest; (Cant.) to wear",
    "\u7530": "field, arable land, cultivated",
    "\u94c1": "iron; strong, solid, firm",
    "\u63a7": "accuse, charge; control",
    "\u7a0e": "taxes",
    "\u5de6": "left; east; unorthodox, improper",
    "\u53f3": "right; west; right-wing",
    "\u4efd": "portion, part; duty",
    "\u7a7f": "penetrate, pierce, drill; wear",
    "\u827a": "art; talent, ability; craft",
    "\u80cc": "back; back side; behind; betray",
    "\u9635": "column, row or file of troops",
    "\u8349": "grass, straw, thatch, herbs",
    "\u811a": "leg, foot; base, leg, foundation",
    "\u6982": "generally, approximately",
    "\u6076": "evil, wicked, bad, foul",
    "\u5757": "piece, lump; dollar",
    "\u987f": "pause, stop; bow, kowtow; arrange",
    "\u6562": "to dare, venture; bold, brave",
    "\u5b88": "defend, protect, guard, conserve",
    "\u9152": "wine, spirits, liquor, alcoholic beverage",
    "\u5c9b": "island",
    "\u6258": "to hold up with palm; to support, rely on",
    "\u592e": "center, conclude, run out; beg",
    "\u6237": "door; family",
    "\u70c8": "fiery, violent, vehement, ardent",
    "\u6d0b": "ocean, sea; foreign; western",
    "\u54e5": "elder brother",
    "\u7d22": "large rope, cable; rules, laws; to demand, to exact; to search, inquire; isolated",
    "\u80e1": "recklessly, foolishly; wildly",
    "\u6b3e": "item, article; clause; fund",
    "\u9760": "lean on, trust, depend on; near",
    "\u8bc4": "appraise, criticize, evaluate",
    "\u7248": "printing blocks; edition",
    "\u5b9d": "treasure, jewel; precious, rare",
    "\u5ea7": "seat; stand, base",
    "\u91ca": "interprete, elucidate; release",
    "\u666f": "scenery, view; conditions",
    "\u987e": "look back; look at; look after",
    "\u5f1f": "young brother; junior; i, me",
    "\u767b": "rise, mount, board, climb",
    "\u8d27": "goods, commodities, products",
    "\u4e92": "mutually, reciprocally",
    "\u4ed8": "give, deliver, pay, hand over; entrust",
    "\u4f2f": null,
    "\u6162": "slow(ly), leisurely, sluggish",
    "\u6b27": "translit.: Europe; ohm; surname",
    "\u6362": "change",
    "\u95fb": "hear; smell; make known; news",
    "\u5371": "dangerous, precarious; high",
    "\u5fd9": "busy, pressed for time; hustling",
    "\u6838": "seed, kernel, core, nut; atom",
    "\u6697": "dark; obscure; in secret, covert",
    "\u59d0": "elder sister, young lady",
    "\u4ecb": "forerunner, herald, harbinger; to lie between; sea shell; to wear armor",
    "\u574f": "rotten, spoilt, bad, broken down",
    "\u8ba8": "to discuss; ask for, beg; demand; dun; marry",
    "\u4e3d": "beautiful, magnificent, elegant",
    "\u826f": "good, virtuous, respectable",
    "\u5e8f": "series, serial order, sequence",
    "\u5347": "arise, go up; hoist; advance",
    "\u76d1": "supervise, control, direct",
    "\u4e34": "draw near, approach; descend",
    "\u4eae": "bright, brilliant, radiant, light",
    "\u9732": "dew; bare, open, exposed",
    "\u6c38": "long, perpetual, eternal, forever",
    "\u547c": "breathe sigh, exhale; call, shout",
    "\u5473": "taste, smell, odor; delicacy",
    "\u91ce": "open country, field; wilderness",
    "\u67b6": "rack, stand, prop; prop up",
    "\u57df": "district, region, boundary; land",
    "\u6c99": "sand, gravel, pebbles; granulated",
    "\u6389": "turn, move; shake, wag; drop down",
    "\u62ec": "include, embrace, enclose",
    "\u8230": "warship",
    "\u9c7c": "fish; surname; KangXi radical 195",
    "\u6742": "mixed, blended; mix, mingle",
    "\u8bef": "err, make mistake; interfere",
    "\u6e7e": "bay, cove, inlet, bend of stream",
    "\u5409": "lucky, propitious, good",
    "\u51cf": "decrease, subtract, diminish",
    "\u7f16": "knit, weave; arrange; compile",
    "\u695a": "name of feudal state; clear",
    "\u80af": "willing; consent to, permit",
    "\u6d4b": "measure, estimate, conjecture",
    "\u8d25": "be defeated, decline, fail",
    "\u5c4b": "house; room; building, shelter",
    "\u8dd1": "run, flee, leave in hurry",
    "\u68a6": "dream; visionary; wishful",
    "\u6563": "scatter, disperse, break up",
    "\u6e29": "lukewarm",
    "\u56f0": "to surround, beseige; to be surrounded; difficult",
    "\u5251": "sword, dagger, saber",
    "\u6e10": "gradually",
    "\u5c01": "letter, envelope; feudal",
    "\u6551": "save, rescue, relieve; help, aid",
    "\u8d35": "expensive, costly, valuable",
    "\u67aa": "spear, lance; gun, rifle",
    "\u7f3a": "be short of, lack; gap, deficit",
    "\u697c": "building of two or more stories",
    "\u53bf": "county, district, subdivision",
    "\u5c1a": "still, yet; even; fairly, rather",
    "\u6beb": "fine hair; measure of length",
    "\u79fb": "change place, shift; move about",
    "\u5a18": "mother; young girl; woman; wife",
    "\u670b": "friend, pal, acquaintance",
    "\u753b": "a painting, picture, drawing; to draw",
    "\u73ed": "class, group, grade; squad; job",
    "\u667a": "wisdom, knowledge, intelligence",
    "\u4ea6": "also, too; likewise",
    "\u8033": "ear; merely, only; handle",
    "\u6069": "kindness, mercy, charity",
    "\u77ed": "short; brief; deficient, lacking",
    "\u638c": "palm of hand, sole of foot, paw",
    "\u6050": "fear; fearful, apprehensive",
    "\u9057": "lose; articles lost; omit",
    "\u56fa": "to become solid, solidify; strength",
    "\u5e2d": "seat; mat; take seat; banquet",
    "\u677e": "pine tree; fir tree",
    "\u79d8": "secret, mysterious, abstruse",
    "\u8c22": "thank; decline",
    "\u9c81": "foolish, stupid, rash; vulgar",
    "\u9047": "meet, come across, encounter",
    "\u5eb7": "peaceful, quiet; happy, healthy",
    "\u8651": "be concerned, worry about",
    "\u5e78": "luck(ily), favor, fortunately",
    "\u5747": "equal, even, fair; all, also",
    "\u9500": "melt, fuse; market, sell",
    "\u949f": "clock; bell",
    "\u8bd7": "poetry; poem, verse, ode",
    "\u85cf": "hide, conceal; hoard, store up",
    "\u8d76": "pursue, follow; expel, drive away",
    "\u5267": "theatrical plays, opera, drama",
    "\u7968": "slip of paper or bamboo; ticket",
    "\u635f": "diminish; impair; injure",
    "\u5ffd": "suddenly, abruptly; neglect",
    "\u5de8": "large, great, enormous; chief",
    "\u70ae": "large gun, cannon; artillery",
    "\u65e7": "old, ancient; former, past",
    "\u7aef": "end, extreme; head; beginning",
    "\u63a2": "find, locate; search, grope for",
    "\u6e56": "a lake; Hubei, Hunan; bluish-green",
    "\u5f55": "copy, write down, record",
    "\u53f6": "to harmonize, to rhyme; to unite; (borrowed for) leaf",
    "\u6625": "spring; wanton",
    "\u4e61": "country; rural; village",
    "\u9644": "adhere to, append; rely on near to",
    "\u5438": "inhale, suck in; absorb; attract",
    "\u4e88": "I, me; to give",
    "\u793c": "social custom; manners; courtesy",
    "\u6e2f": "port, harbor; small stream; bay",
    "\u96e8": "rain; rainy; KangXi radical 173",
    "\u5440": "particle used to express surprise or mild emphasis; (Cant.) slurred form of the number ten",
    "\u677f": "plank, board; iron or tin plate",
    "\u5ead": "courtyard; spacious hall or yard",
    "\u5987": "married women; woman; wife",
    "\u5f52": "return; return to, revert to",
    "\u775b": "eyeball; pupil of eye",
    "\u996d": "cooked rice; food, meal",
    "\u989d": "forehead; tablet, plaque; fixed",
    "\u542b": "hold in mouth; cherish; contain",
    "\u987a": "obey, submit to, go along with",
    "\u8f93": "transport, carry, haul",
    "\u6447": "wag, swing, wave; shake; scull",
    "\u62db": "beckon, summon; recruit, levy",
    "\u5a5a": "get married; marriage, wedding",
    "\u8131": "take off",
    "\u8865": "mend, patch, fix, repair, restore",
    "\u8c13": "say, tell; call, name; be called",
    "\u7763": "supervise, oversee, direct",
    "\u6bd2": "poison, venom; poisonous",
    "\u6cb9": "oil, fat, grease, lard; paints",
    "\u7597": "be healed, cured, recover",
    "\u65c5": "trip, journey; travel; traveler",
    "\u6cfd": "marsh, swamp; grace, brilliance",
    "\u6750": "material, stuff; timber; talent",
    "\u706d": "extinguish; wipe out, exterminate",
    "\u9010": "chase, expel; one by one",
    "\u83ab": "do not, is not, can not; negative",
    "\u7b14": "writing brush; write; stroke",
    "\u4ea1": "death, destroyed; lose, perish",
    "\u9c9c": "fresh; delicious; attractive",
    "\u8bcd": "words; phrase, expression",
    "\u5723": "holy, sacred",
    "\u62e9": "select, choose, pick out",
    "\u5bfb": "seek, search, look for; ancient",
    "\u5382": "factory, workshop; radical 27",
    "\u7761": "sleep, doze",
    "\u535a": "gamble, play games; wide, broad",
    "\u52d2": "strangle, tighten",
    "\u70df": "smoke, soot; opium; tobacco, cigarettes",
    "\u6388": "give to, transmit; confer",
    "\u8bfa": "promise; assent, approve",
    "\u4f26": "normal human relationships",
    "\u5cb8": "bank, shore; beach, coast",
    "\u5965": "mysterious, obscure, profound",
    "\u5510": "Tang dynasty; Chinese",
    "\u5356": "sell; betray; show off",
    "\u4fc4": "sudden(ly), soon; Russian",
    "\u70b8": "to fry in oil; to scald; to explode",
    "\u8f7d": "load; carry; transport, convey",
    "\u6d1b": "river in Shanxi province; city",
    "\u5065": "strong, robust, healthy; strength",
    "\u5802": "hall; government office",
    "\u65c1": "side; by side, close by, near",
    "\u5bab": "palace",
    "\u559d": "drink; shout, call out",
    "\u501f": "borrow; lend; make pretext of",
    "\u541b": "sovereign, monarch, ruler, chief, prince",
    "\u7981": "restrict, prohibit, forbid",
    "\u9634": null,
    "\u56ed": "garden; park, orchard",
    "\u8c0b": "plan, scheme; strategem",
    "\u5b8b": "Song dynasty; surname",
    "\u907f": "avoid; turn aside; escape; hide",
    "\u6293": "scratch; clutch, seize, grab",
    "\u8363": "glory, honor; flourish, prosper",
    "\u59d1": null,
    "\u5b59": "grandchild, descendent; surname",
    "\u9003": "escape, flee; abscond, dodge",
    "\u7259": "tooth, molars, teeth; serrated",
    "\u675f": "bind, control, restrain; bale",
    "\u8df3": "jump, leap, vault, bounce; dance",
    "\u9876": "top, summit, peak; to carry on the head"
}
const values = Object.values(jsonData)

const randomValue = values[parseInt(Math.random() * values.length)]

console.log(randomValue)
